.vscode/extensions.json
.vscode/settings.json
.vscode/tasks.json
README.md

:construction: Add prettier on save for VS Code.
- The VS Code editor will automatically `prettify` the code files. :sparkles:

Add prettier on save for VS Code

---

.gitignore
README.md
docker-compose.yml

feat: docker compose

---

src/shared/filter/all-exceptions.filter.spec.ts
src/shared/filter/all-exceptions.filter.ts
src/shared/shared.module.ts

- all exception handler added in the shared module
- Error stack added in logging

all exception handler

---

src/shared/filter/all-exceptions.filter.spec.ts
src/shared/filter/all-exceptions.filter.ts

- fix object type exception message response
- unit test all exception filter

unit test for all exception filter

---

.gitignore
package-lock.json
package.json

- To run doc server in watch mode run `npm run doc:serve` 
- To generate documentation run `npm run doc:serve`

doc generator configured with compodoc

---

README.md
package-lock.json
src/auth/auth.controller.ts
src/auth/auth.module.ts
src/auth/auth.service.ts
src/shared/filter/all-exceptions.filter.spec.ts
src/user/user.module.ts

- Update `README` file.
- Update `import` paths. Absolute paths seems to be failing the `e2e` test for some reason.

Update README and import paths for test

---

src/auth/auth.controller.ts
src/auth/auth.service.ts
src/auth/dto/register.dto.ts
src/user/dto/add-user.dto.ts
src/user/user.service.ts

Register api returns:
```
{
"id": 5,
"email": "tanveer@monstar-lab.com",
"name": "Tanveer"
}
```
Closes #17

feat(auth): return created user from register api

---

src/auth/auth.controller.ts
src/auth/auth.module.ts
src/auth/dto/login.dto.ts
src/auth/dto/register.dto.ts
src/main.ts
src/shared/config/configuration.ts
src/shared/config/module-options.ts

- Use global validation pipe
- Add JWT env var `expiresAt` validation
- Request body validation for login, registration
- Swagger doc for login, registration
closes #19, #18 #15

Auth validation

---

src/auth/auth.controller.ts
src/auth/auth.module.ts
src/auth/auth.service.ts
src/auth/dto/login.dto.ts
src/auth/guards/jwt-auth.guard.ts
src/auth/guards/local-auth.guard.ts
src/auth/strategies/jwt.strategy.ts
src/auth/strategies/local.strategy.ts
src/user/user.controller.ts
src/user/user.module.ts

- Added authentication guard for `local` strategy.
- Added authentication guard for `jwt` strategy.
- Change `login` parameter from `username` -> `email`.
Closes #14

Authentication Guards

---

.github/workflows/integrate.yml
README.md

Add tests badge

---

.github/workflows/build-workflow.yml
.github/workflows/integrate.yml
.github/workflows/tests-workflow.yml
README.md

Add build workflow and badge

---

commitlint.config.js
package-lock.json
package.json

feat: add commitlint package
Uses husky `commit-msg` hook to run it before every commit.
https://github.com/conventional-changelog/commitlint

feat: add commitlint package

---

src/user/user.module.ts
src/user/user.repository.ts
src/user/user.service.ts

Adding custom repository for db interactions. 
Link shared by Tanveer : https://docs.nestjs.com/techniques/database#custom-repository

feat: User repository

---

src/user/user.repository.spec.ts

Custom User Repository Unit tests.
User Repo PR : #38

feat: init test module for user repository

---

test/auth/auth.e2e-spec.ts

e2e tests for auth register endpoint .

feat: e2e tests for auth register

---

src/user/entities/user.entity.ts
src/user/services/user.service.ts

feat: user service - user create

feat: user service - user create

---

src/auth/controllers/auth.controller.spec.ts
src/auth/controllers/auth.controller.ts
src/auth/services/auth.service.spec.ts
src/auth/services/auth.service.ts
src/user/services/user.service.spec.ts
test/auth/auth.e2e-spec.ts

- unit test for
- AuthController `refreshToken`
- AuthService `validateUser`, `login`, `register`, `refreshToken`, `getAuthToken`
- UserService `createUser`, `findById`, `validateUsernamePassword`
- e2e test for
- AuthController `login`, `refreshToken` action
- fix response header code for login, refresh-token action (200)
- fix refresh-token exception type while the user is invalid

Unit test, e2e test for Auth module, User module

---

src/auth/auth.module.ts
src/auth/constants/strategy.constant.ts
src/auth/guards/jwt-auth.guard.ts
src/auth/guards/jwt-refresh.guard.ts
src/auth/guards/local-auth.guard.ts
src/auth/strategies/jwt-auth.strategy.ts
src/auth/strategies/jwt-refresh.strategy.ts
src/auth/strategies/local.strategy.ts

- Add return types
- Use consts over strings
- Add comments in guards

Auth Module - Minor refactor

---

src/auth/controllers/auth.controller.spec.ts
src/auth/controllers/auth.controller.ts
src/auth/services/auth.service.spec.ts
src/shared/dtos/pagination-params.dto.ts
src/user/controllers/user.controller.spec.ts
src/user/controllers/user.controller.ts
src/user/services/user.service.spec.ts
src/user/services/user.service.ts
test/auth/auth.e2e-spec.ts
test/user/user.e2e-spec.ts

Users list endpoint
auth controller to data - meta output format

feat: users list and auth format

---

src/auth/dtos/auth-register-input.dto.ts
src/auth/services/auth.service.ts
src/user/dtos/user-create-input.dto.ts

feat: fix roles in register DTO

feat: fix roles in register DTO - Minor fix

---

src/auth/dtos/auth-register-output.dto.ts
src/auth/dtos/auth-token-output.dto.ts
src/auth/services/auth.service.ts

fix: expose in auth output dtos

---

src/shared/errors/base-api-error.ts
src/shared/filters/all-exceptions.filter.spec.ts
src/shared/filters/all-exceptions.filter.ts
test/auth/auth.e2e-spec.ts
test/user/user.e2e-spec.ts

New Error Format 
New format
```
{
"error": {
"statusCode": 404,
"message": "Not Found",
"errorName": "NotFoundException",
"details": {
"statusCode": 404,
"message": "Not Found"
},
"path": "/api/v1/users/11",
"requestId": "35553e9e-1710-4bfd-877b-d4710a03394d",
"timestamp": "2020-12-18T07:49:18.899Z"
}
}
```

feat: new error format

---

package.json
src/user/controllers/user.controller.ts
src/user/dtos/user-update-input.dto.ts

feat: authorization - Minor comments

feat: authorization - Minor comments

---

src/auth/dtos/auth-register-input.dto.ts
src/auth/services/auth.service.spec.ts
src/auth/services/auth.service.ts
test/auth/auth.e2e-spec.ts

feat: prevent disabled user account from logging in

feat: prevent disabled user account from logging in

---

README.md

feat: update README - Minor change

---

README.md
sonar-project.properties

feat: remove old sonarqube badges

feat: remove old sonarqube badges

---

README.md

feat: update README badges

---

src/shared/acl/acl-rule.constant.ts
src/shared/acl/acl.service.spec.ts
src/shared/acl/acl.service.ts
src/shared/acl/action.constant.ts
src/shared/acl/subject.constant.ts
src/shared/constants/common.ts
src/user/services/user-acl.service.spec.ts
src/user/services/user-acl.service.ts
src/user/user.module.ts

In service layer, usage should be like
```
if(!this.aclService.forUser(user).canDoAction(Action.Update, otherUser)){
UnauthorizedException('User do not have permission for this action');
}

feat: acl base service, user acl service implementation

---

.github/workflows/sonarqube-workflow.yml
.gitignore
package-lock.json
package.json
sonar-project.properties

https://github.com/3dmind/jest-sonar-reporter

Get sonarcloud test coverage

---

README.md
package-lock.json
package.json
src/cli.ts
src/main.ts
src/shared/interceptors/logging.interceptor.spec.ts
src/shared/interceptors/logging.interceptor.ts
src/shared/logger/logger.module.ts
src/shared/logger/logger.service.spec.ts
src/shared/logger/logger.service.ts
src/shared/shared.module.ts

Replace Pino with Winston Logger - Part 1/3
- Currently the `RequestID` will not be logged in each log. 
- We will fix this in Part 2/3.

Replace Pino with Winston Logger - Part 1/3

---

src/article/services/article.service.spec.ts
src/article/services/article.service.ts
src/auth/controllers/auth.controller.spec.ts
src/auth/controllers/auth.controller.ts
src/auth/services/auth.service.spec.ts
src/auth/services/auth.service.ts
src/auth/strategies/local.strategy.ts
src/cli.ts
src/shared/request-context/req-context.decorator.ts
src/shared/request-context/request-context.dto.ts
src/shared/request-context/util/index.spec.ts
src/shared/request-context/util/index.ts
src/user/controllers/user.controller.spec.ts
src/user/controllers/user.controller.ts
src/user/services/user.service.spec.ts
src/user/services/user.service.ts
test/test-utils.ts

- new logs with context in auth modules and user module
TODO: consistency of logs (bw normal logs and logs called from interceptors for req & resp)

logs with context part 4/4

---

src/auth/controllers/auth.controller.spec.ts
src/auth/controllers/auth.controller.ts
src/auth/dtos/auth-token-output.dto.ts
src/auth/services/auth.service.spec.ts
src/auth/services/auth.service.ts
src/auth/strategies/local.strategy.ts
src/shared/filters/all-exceptions.filter.spec.ts
src/shared/filters/all-exceptions.filter.ts
src/shared/interceptors/logging.interceptor.ts
src/shared/logger/logger.service.ts
src/user/controllers/user.controller.ts

Substitute req.user with ctx.user

user from ctx

---

src/app.controller.spec.ts
src/app.controller.ts
src/app.service.ts
src/auth/controllers/auth.controller.spec.ts
src/auth/controllers/auth.controller.ts
src/auth/services/auth.service.spec.ts
src/auth/services/auth.service.ts
src/auth/strategies/local.strategy.ts
src/cli.ts
src/main.ts
src/shared/filters/all-exceptions.filter.spec.ts
src/shared/filters/all-exceptions.filter.ts
src/shared/interceptors/logging.interceptor.ts
src/shared/logger/logger.service.ts
src/user/controllers/user.controller.spec.ts
src/user/controllers/user.controller.ts
src/user/services/user.service.spec.ts
src/user/services/user.service.ts

Removes the `implements LoggerService` implementation. 
Removes the `app.useLogger(new AppLogger())`.

feat: logger service funtions

---

.eslintrc.js
package-lock.json
package.json
src/app.module.ts

Importing @war1oc's PR from BDOT  
Run `npm run lint:fix` to fix all files.
Plugin used: https://github.com/lydell/eslint-plugin-simple-import-sort
other packages used: https://www.npmjs.com/package/lint-staged

feat: import order plugin with example

---

LICENSE.md
README.md

docs: add license
